<h1 align="center">More Exceptions</h1>

- First created a class named Calculator.
- Inside the class created a int return type method named power that takes two integer parameters n and p followed by throws Exception keywords.
- Inside the method defined an if condition.
- If n is smaller than 0 or p is smaller than 0 throw a user defined exception using throw keyword.
- Else return the integer type output of pow() method of Math package; n and p passed as arguments.
- Then declared the main class with main method.
- Inside the main method created an object of Scanner class named in that takes user input.
- Then declared an integer variable t that takes integer user input.
- Then defined a while loop that runs till t is greater than 0.
- Inside the loop, declared two integer variables n and p that stores integer user input.
- Then created object of Calculator class named calc.
- Then defined a try-catch block.
- Inside the try block declared an integer variable ans that stores the output of power() method with n and p as arguments.
- And printing the ans variable value.
- Inside the catch block printing the exception caught.
- Hence providing the output.